[package]
description = "A wasmer tunables library for memory limits."
license = "Apache-2.0"
homepage = "https://github.com/Cyrux-Network/cyrux-blockchain"
name = "cyrux-wasmer-tunables"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmer = "3"

