[workspace]
[package]
name = "example"
version = "0.1.0"
authors = ["<author>"]
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["ink", "scale", "scale-info"]

[dependencies]
ink = { version = "4", default-features = false }
pink-s3 = { default-features = false, path = ".." }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"], optional = true }


[dev-dependencies]
pink-chain-extension = { path = "../../../pink/chain-extension" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "pink-s3/std",
    "ink/std",
    "scale-info/std",
]
ink-as-dependency = []
