[package]
name = "system"
version = "1.2.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["ink", "scale", "scale-info"]

[dependencies]
ink = { version = "4", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"], optional = true }

pink = { default-features = false, path = "../../pink/pink" }
this-crate = { path = "../../this-crate" }

[lib]
name = "system"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "pink/std",
]
ink-as-dependency = []
