[package]
description = "The runtime that runs Phat SideVM instance"
license = "Apache-2.0"
homepage = "https://github.com/Cyrux-Network/cyrux-blockchain"
edition = "2021"
name = "sidevm-host-runtime"
version = "0.1.1"

[dependencies]
anyhow = "1.0.69"
dashmap = "5.2.0"
futures = "0.3"
hex_fmt = "0.3.0"
log = "0.4.16"
tracing = "0.1"
sidevm-env = { version = "0.2.0-alpha.7", path = "../env", features = ["host"] }
thread_local = "1.1"
tokio = { version = "1.24.2", features = ["full"] }
wasmer = "3"
wasmer-wasix-types = "0.4.0"
wasmer-compiler-singlepass = "3"
wasmer-compiler-cranelift = { version = "3", optional = true }
wasmer-compiler-llvm = { version = "3", optional = true }
cyrux-wasmer-tunables = { version = "0.1", path = "../../cyrux-wasmer-tunables" }
wasmer-middlewares = "3"
parity-wasm = "0.45.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
thiserror = "1"
libc = "0.2"
scale = { version = "3.6.5", package = "parity-scale-codec" }
tokio-rustls = "0.23"
rustls-pemfile = "1"
webpki-roots = "0.22"
once_cell = "1"
cyrux-tokio-proxy = "0.1.0"
page_size = "0.6.0"
cyrux-scheduler = { version = "0.1", path = "../../cyrux-scheduler" }
derive_more = "0.99.17"
rocket = { version = "0.5.0", optional = true }
trust-dns-resolver = { version = "0.23.2", features = ["tokio"] }

[features]
default = ["rocket-stream"]
rocket-stream = ["rocket"]
