[package]
description = "The memory allocator for cyrux pruntime"
license = "Apache-2.0"
homepage = "https://github.com/Cyrux-Network/cyrux-blockchain"
name = "cyrux-allocator"
version = "0.1.0"
edition = "2018"

[dependencies]
