[package]
name = "sidevm_deployer"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"
description = "This is a demo describes how to write a pink driver contract"

[package.metadata.cargo-machete]
ignored = ["ink", "scale", "scale-info"]

[dependencies]
ink = { version = "4", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"], optional = true }

pink = { default-features = false, path = "../../pink/pink" }
system = { version = "1.0", default-features = false, path = "../system" }
this-crate = { path = "../../this-crate" }
hex_fmt = "0.3"

[dev-dependencies]
insta = "1.32"
tracing-subscriber = "0.3"
pink-chain-extension = { default-features = false, path = "../../pink/chain-extension" }

[lib]
name = "sidevm_deployer"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "pink/std",
    "system/std",
]
ink-as-dependency = []
